version: "3.8"

services:
  backend:
    build: src/backend
    volumes:
      - ./src/backend:/srv
    ports:
      - "8000:8000"

  frontend:
    build: src/frontend
    volumes:
      - ./src/frontend:/srv
      - node_modules:/srv/node_modules
    ports:
      - "8080:8080"
    environment:
     - NODE_ENV="development"

volumes:
  node_modules:
