# Generated by Django 4.0 on 2021-12-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='serverPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.PositiveIntegerField()),
                ('server_preferences_name', models.CharField(max_length=1000)),
                ('server_preferences_value', models.TextField()),
            ],
        ),
    ]
