# Generated by Django 4.0 on 2021-12-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_serverpreferences_policy_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverpreferences',
            name='server_preferences_value',
            field=models.CharField(max_length=100000),
        ),
    ]
