# Generated by Django 4.0 on 2021-12-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_serverpreferences_server_preferences_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='pluginPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.PositiveIntegerField()),
                ('plugin_name', models.CharField(max_length=1000)),
                ('plugin_id', models.PositiveIntegerField()),
                ('full_name', models.CharField(max_length=1000)),
                ('preference_name', models.CharField(max_length=1000)),
                ('preference_type', models.CharField(max_length=1000)),
                ('preference_values', models.CharField(max_length=1000)),
                ('selected_value', models.CharField(max_length=1000)),
            ],
        ),
    ]
