# Generated by Django 4.0 on 2021-12-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pluginpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='familySelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.PositiveIntegerField()),
                ('family_name', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
            ],
        ),
    ]
