# Generated by Django 4.0 on 2021-12-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_familyselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='individualPluginSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.PositiveIntegerField()),
                ('plugin_id', models.PositiveIntegerField()),
                ('plugin_name', models.CharField(max_length=1000)),
                ('family', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1000)),
            ],
        ),
    ]
