# Generated by Django 4.0 on 2021-12-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_reporthost'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_host_id', models.PositiveIntegerField()),
                ('tag_name', models.CharField(max_length=1000)),
                ('tag_value', models.CharField(max_length=1000)),
            ],
        ),
    ]
