# Generated by Django 4.0 on 2021-12-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_reportitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportItemProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_host_id', models.PositiveIntegerField()),
                ('property_name', models.CharField(max_length=1000)),
                ('property_value', models.CharField(max_length=100000)),
            ],
        ),
    ]
