# Generated by Django 4.0 on 2021-12-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_reportitemproperties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportitem',
            old_name='plugin_family',
            new_name='pluginFamily',
        ),
        migrations.RenameField(
            model_name='reportitem',
            old_name='plugin_id',
            new_name='pluginID',
        ),
        migrations.RenameField(
            model_name='reportitem',
            old_name='plugin_name',
            new_name='pluginName',
        ),
    ]
