# Generated by Django 4.0 on 2021-12-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_plugin_family_reportitem_pluginfamily_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportitemproperties',
            old_name='report_host_id',
            new_name='report_item_id',
        ),
    ]
