# Generated by Django 4.0 on 2021-12-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_report_host_id_reportitemproperties_report_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pluginpreferences',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='pluginpreferences',
            old_name='plugin_id',
            new_name='pluginId',
        ),
        migrations.RenameField(
            model_name='pluginpreferences',
            old_name='plugin_name',
            new_name='pluginName',
        ),
        migrations.RenameField(
            model_name='pluginpreferences',
            old_name='preference_name',
            new_name='preferenceName',
        ),
        migrations.RenameField(
            model_name='pluginpreferences',
            old_name='preference_type',
            new_name='preferenceType',
        ),
        migrations.RenameField(
            model_name='pluginpreferences',
            old_name='preference_values',
            new_name='preferenceValues',
        ),
        migrations.RenameField(
            model_name='pluginpreferences',
            old_name='selected_value',
            new_name='selectedValue',
        ),
    ]
