# Generated by Django 4.0 on 2021-12-26 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_full_name_pluginpreferences_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualpluginselection',
            old_name='family',
            new_name='Family',
        ),
        migrations.RenameField(
            model_name='individualpluginselection',
            old_name='plugin_id',
            new_name='PluginId',
        ),
        migrations.RenameField(
            model_name='individualpluginselection',
            old_name='plugin_name',
            new_name='PluginName',
        ),
        migrations.RenameField(
            model_name='individualpluginselection',
            old_name='status',
            new_name='Status',
        ),
    ]
