# Generated by Django 4.0 on 2021-12-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_family_name_familyselection_familyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportitemproperties',
            name='property_value',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='serverpreferences',
            name='server_preferences_value',
            field=models.CharField(max_length=1000000),
        ),
    ]
