# Generated by Django 4.0 on 2021-12-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_reportitemproperties_property_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='file_hash',
            field=models.CharField(default='default_hash', max_length=32),
            preserve_default=False,
        ),
    ]
